### ISSUE TITLE
Visual Studio 2022 is not supported

### ISSUE THREAD

**Issue by tsharp** [tsharp/D365DeveloperExtensions#12]
The latest version of the Extension is not compatible with vs2022 (according to the marketplace manifest checker ...)

**Comment by Dehantor** [comment]
When are you planning to make a project for Visual Studio 2022

**Comment by peterwidmer** [comment]
Hi, 

first of all a big thank you for doing this extension!
I'd also need support for VS-2022 - do you have a plan to migrate it and if so, when?

**Comment by tsharp** [comment]
Heya @Dehantor and @peterwidmer - sorry for the late response here. I will be working on VS 2022 support this month.

**Comment by peterwidmer** [comment]
Thank you, this is highly appreciated!

**Comment by FrankZhu1020** [comment]
Hi,

first of all a big thank you for doing this extension!
I'd also need support for VS-2022 - do you have a plan to migrate it and if so, when?

**Comment by peterwidmer** [comment]
Hi @tsharp 

will you be able to look into it or do you feel more like that you'll abandon this extension and we'll have to look into another solution?

Thank you
Peter

**Comment by tsharp** [comment]
@peterwidmer 
@FrankZhu1020 
@Dehantor 

I have released a preview version of the extension here: https://marketplace.visualstudio.com/items?itemName=tsharp.D365DeveloperExtensionsModern

This should correctly add support for VS 2022. I will be doing more testing over the next few weeks or so but please do let me know / file issues if you run into any problems. Cheers!

**Comment by kkoTuTo** [comment]
Hi tsharp!
You are amazing, like a **superhero**! 
Thanks for the update, I will use it and test it next time.
But I can't open the link to download the extension at the moment, can you send it to my email?
**cheers**!

**Comment by tsharp** [comment]
@FrankZhu1020 - sorry about that. The extension is now public and you should be able to install directly from Visual Studio 2022 now :)

**Comment by kkoTuTo** [comment]
@tsharp 
It's ok now, thanks superhero！

**Comment by peterwidmer** [comment]
@tsharp 

So far it looks very good, as we installed it on several machines! :-)
If we should have any issued, I'd let you know.

Thank you so much!!

**Comment by wd21sos** [comment]
@tsharp 
VS 2022 crashes when trying to connect with D365 Environment. Latest Version installed!
