### ISSUE TITLE
Cannot create a new webresource

### ISSUE THREAD

**Issue by maerger** [tsharp/D365DeveloperExtensions#3]
![image](https://user-images.githubusercontent.com/6177363/108691654-063a5980-74fc-11eb-9e97-ec5b6589645c.png)

**Comment by tsharp** [comment]
What version of Dynamics is this for? Onlne/OnPrem? v8/v9?

**Comment by maerger** [comment]
online v9

**Comment by PaladinMattt** [comment]
> online v9

This is actually a CRM restriction, you cannot have the hyphen (-) in the web resource name, you can change it to an underscore (_) or just remove it.

**Comment by tsharp** [comment]
Correct, this is a limitation of Dynamics 365 (CRM) and not necessarily this extension. If the behavior desired is different (and within reason) I am open to suggestions.
